name: box-and-products-yii2

volumes:
  db-data:

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./:/app:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "${NGINX_PORT:-1945}:80"

  php:
    build:
      context: ./docker
      dockerfile: php.dockerfile
    user: 1000:1000
    working_dir: /app
    volumes:
      - ./:/app

  db:
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/dumps:/dumps
    working_dir: /dumps
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_HOST_AUTH_METHOD: trust
      # POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}



