name: test-jobs-yii2

volumes:
  db-data:

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./:/app:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "${NGINX_PORT:-1945}:80"

  php:
    build:
      context: ./docker
      dockerfile: php.dockerfile
    user: 1000:1000
    working_dir: /app
    volumes:
      - ./:/app

  db:
    image: mariadb:latest
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/dumps:/dumps
    working_dir: /dumps
    environment:
      MARIADB_DATABASE: ${DB_NAME:-db}
      MARIADB_USER: ${DB_USER:-db}
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      MARIADB_PASSWORD: ${DB_PASS}



